### ISSUE TITLE
Making existing fields translatable is not working with Django 2.1

### ISSUE THREAD

**Issue by floa93** [django-parler/django-parler#254]
Django                            2.1.12
django-parler                     2.0

Prerequisites:
1. Create a new project and app
2. Add a new model( to follow the migration guide at https://django-parler.readthedocs.io/en/stable/advanced/migrating.html):
`class MyModel(models.Model):
    name = models.CharField(max_length=123)`
3. Create and run the migration with makemigration

Making existing fields translatable(like explained in the documentation https://django-parler.readthedocs.io/en/stable/advanced/migrating.html)
1. Change the model to :
class MyModel(TranslatableModel):
    name = models.CharField(max_length=123)

    translations = TranslatedFields(
          name=models.CharField(max_length=123),
    )

2. Create the migration with makemigration
-> Error that the name field already exists( see https://github.com/django-parler/django-parler/issues/154 )
-> rename the TranslatedField to translations_t and create the migration
3. Run the migration with migrate ... 
-> AttributeError: type object 'MyModel' has no attribute '_parler_meta

Whatever you do, you always receive the attribute error that the model does not contain the parler_meta attribute

Regards

**Comment by floa93** [comment]
Here is the additional traceback to the error:

>   File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/projects/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\virtualenvs\lib\site-packages\django\core\management\commands\migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\migration.py", line 114, in apply
    operation.state_forwards(self.app_label, project_state)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\operations\models.py", line 85, in state_forwards
    list(self.managers),
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 97, in add_model
    self.reload_model(app_label, model_name)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 158, in reload_model
    self._reload(related_models)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 191, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 306, in render_multiple
    model.render(self)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 574, in render
    return type(self.name, bases, body)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\models\base.py", line 299, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\migrations\state.py", line 337, in register_model
    self.do_pending_operations(model)
  File "C:\Users\virtualenvs\lib\site-packages\django\apps\registry.py", line 420, in do_pending_operations
    function(model)
  File "C:\Users\virtualenvs\lib\site-packages\django\apps\registry.py", line 399, in apply_next_model
    self.lazy_model_operation(next_function, *more_models)
  File "C:\Users\virtualenvs\lib\site-packages\django\apps\registry.py", line 385, in lazy_model_operation
    function()
  File "C:\Users\virtualenvs\lib\site-packages\django\db\models\fields\related.py", line 316, in resolve_related_class
    field.do_related_class(related, model)
  File "C:\Users\virtualenvs\lib\site-packages\django\db\models\fields\related.py", line 387, in do_related_class
    self.contribute_to_related_class(other, self.remote_field)
  File "C:\Users\virtualenvs\lib\site-packages\parler\fields.py", line 54, in contribute_to_related_class
    self.model.contribute_translations(cls)
  File "C:\Users\virtualenvs\lib\site-packages\parler\models.py", line 939, in contribute_translations
    base = shared_model._parler_meta
AttributeError: type object 'MyModel' has no attribute '_parler_meta'

**Comment by pbeyeler** [comment]
I am having the same issue with Django 1.11.20 and django-parler 2.0.

**Comment by pbeyeler** [comment]
@floa93: See https://github.com/django-parler/django-parler/issues/157#issuecomment-534440366 for a workaround.

**Comment by floa93** [comment]
@pbeyeler thank you, your solution is working for me too

**Comment by lggwettmann** [comment]
Same here, would be great if this could be fixed :)

**Comment by milkomeda** [comment]
See my comment here for solution and clarificaton. https://github.com/django-parler/django-parler/issues/263#issuecomment-603349951
